# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class AgentDecision(BaseModel):
    thought: typing.Optional[str] = None
    search: typing.Optional["SearchParams"] = None
    direct_reply: typing.Optional[str] = None
    clarifying_question: typing.Optional[str] = None

class SearchParams(BaseModel):
    city: typing.Optional[str] = None
    hospital_name: typing.Optional[str] = None
    limit: typing.Optional[int] = None
    is_count_query: typing.Optional[bool] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
